name: Sync Notebooks

on:
  push:
    paths:
      - 'notebooks/**'
  repository_dispatch:
    types: [sync-notebooks]
  workflow_dispatch:  # This allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Blog Repo
        uses: actions/checkout@v2

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main

      - name: Install Dependencies
        run: |
          pip install nbconvert

      - name: Convert Notebooks to Markdown
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          for notebook in _notebooks/*.ipynb; do
            date=$(date +"%Y-%m-%d")
            title=$(basename "$notebook" .ipynb)
            md_file="_posts/${date}-${title}.md"
            echo "Converting $notebook to $md_file"
            if [ ! -f "$md_file" ]; then
              jupyter nbconvert --to markdown "$notebook" --output "$md_file"
            fi
          done

      - name: Move Images to Assets
        run: |
          mkdir -p assets/notebooks
          for img in _posts/*.md; do
            img_dir=$(dirname "$img")/$(basename "$img" .md)_files
            if [ -d "$img_dir" ]; then
              mv "$img_dir"/* assets/notebooks/
              rm -rf "$img_dir"
            fi
          done

      - name: Update Image Paths
        run: |
          for file in _posts/*.md; do
            sed -i 's|\!\\]*\))|\!\\|g' "$file"
          done

      - name: Add Front Matter
        run: |
          for file in _posts/*.md; do
            if ! grep -q "^---" "$file"; then
              date=$(date +"%Y-%m-%d")
              title=$(basename "$file" .md | sed 's/^[0-9-]*-//')
              echo "---" > temp && cat $file >> temp && mv temp $file
              echo "title: $title" >> $file
              echo "date: $date" >> $file
              echo "layout: post" >> $file
              echo "categories: [Tech, Computational Physics]" >> $file
              echo "---" >> $file
            fi
          done

      - name: Build and Deploy
        run: |
          bundle install
          bundle exec jekyll build
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update notebooks'
          git push origin main
